/**
 * Write docs/reckoner-state.md: a generated snapshot of what the reckoner holds,
 * for Claude chat (via the synced Project) and for anyone planning the next
 * piece of content. It carries no dates, so the same content always produces
 * the same file and a stale snapshot shows up as a diff.
 *
 *   npm run status            write docs/reckoner-state.md
 *   npm run status -- --check exit 1 if it is out of date (part of check:pages)
 */
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { join, resolve } from "node:path";
import { buildFocusIndex, loadGuides, PKG_ROOT } from "./lib/build";
import { FOCUS_AREAS } from "../src/schema/syllabus";
import { loadGame } from "./lib/game";

const REPO = resolve(PKG_ROOT, "..", "..");
const OUT = join(REPO, "docs", "reckoner-state.md");
const check = process.argv.includes("--check");

const quiet = () => {};
const published = loadGuides(join(PKG_ROOT, "content", "guides"), false, quiet);
const all = loadGuides(join(PKG_ROOT, "content", "guides"), true, quiet);
const catalogue: { id: string; name: string; scale: string }[] = JSON.parse(readFileSync(join(PKG_ROOT, "content", "catalogue.json"), "utf8"));
const scales: Record<string, { label: string }> = JSON.parse(readFileSync(join(PKG_ROOT, "content", "questions.json"), "utf8")).SCALE;
const pkg = JSON.parse(readFileSync(join(PKG_ROOT, "package.json"), "utf8"));
const registry = [...readFileSync(join(PKG_ROOT, "scripts", "validate.ts"), "utf8")
  .match(/MODEL_REGISTRY = \[([\s\S]*?)\]/)![1].matchAll(/"([a-z0-9-]+)"/g)].map((m) => m[1]);
const plan = existsSync(join(REPO, "docs", "ACTION-PLAN.md")) ? readFileSync(join(REPO, "docs", "ACTION-PLAN.md"), "utf8") : "";
const itemNumbers = [...plan.matchAll(/^### (\d+)\./gm)].map((m) => +m[1]);
const nextItem = itemNumbers.length ? Math.max(...itemNumbers) + 1 : 1;

const guideIds = new Set(published.map((g) => g.id));
const index = buildFocusIndex(published);
const examples = published.flatMap((g) => g.phases.flatMap((p) => p.examples));
const sequences = published.flatMap((g) => g.workedSequences);
const scale = (s: string) => scales[s]?.label ?? s;
const nameOf = (id: string) => published.find((g) => g.id === id)?.name ?? catalogue.find((m) => m.id === id)?.name ?? id;

const coverage = (Object.keys(FOCUS_AREAS) as (keyof typeof FOCUS_AREAS)[]).flatMap((st) =>
  (FOCUS_AREAS[st] as readonly string[]).map((fa) => {
    const e = index[`${st}|${fa}`];
    const result = e?.sequences.length ? "Ready plan" : e?.examples.length ? "Examples only" : "Start from 5E (empty)";
    return { st, fa, result, seqs: e?.sequences ?? [], exs: e?.examples ?? [] };
  }),
);
const count = (r: string) => coverage.filter((c) => c.result === r).length;

const emptyPhases = published.flatMap((g) => g.phases.filter((p) => !p.examples.length).map((p) => `${g.id} → ${p.id} (${p.name})`));
const comingSoon = published.flatMap((g) => g.nesting.filter((n) => !guideIds.has(n.modelId))
  .map((n) => `${g.id} ${n.role ?? "nests with"} ${n.modelId} (${nameOf(n.modelId)})`));
const drafts = all.filter((g) => g.status !== "published");
const registryRows = registry.map((id) => {
  const where = guideIds.has(id) ? "guide" : drafts.some((g) => g.id === id) ? "draft guide (not shown to students)" : catalogue.some((m) => m.id === id) ? "catalogue" : "MISSING";
  return `| \`${id}\` | ${nameOf(id)} | ${where} |`;
});
const game = loadGame();
const gamePublished = game.lessons.filter((l) => l.status === "published");
const strays = catalogue.filter((m) => !registry.includes(m.id)).map((m) => m.id);

const md = `# Reckoner state

Generated by \`npm run status\` (in \`tools/reckoner\`) from the guide YAML, catalogue and action plan.
**Do not edit by hand.** It is refreshed by \`npm run publish:pages\`, and \`npm run check:pages\` (run in CI)
fails if it is out of date. Read it before drafting reckoner content or a handoff, and trust it over memory.

## At a glance

| | |
|---|---|
| Models in the reckoner | ${published.length + catalogue.filter((m) => !guideIds.has(m.id)).length} |
| Published companion guides | ${published.length} of ${registry.length} registered models |
| Models still in the catalogue (no guide) | ${catalogue.filter((m) => !guideIds.has(m.id)).length} |
| Draft or in-review guides (not shown to students) | ${drafts.length} |
| Examples across published guides | ${examples.length} (${examples.filter((e) => e.kind === "positive").length} positive, ${examples.filter((e) => e.kind === "negative").length} negative) |
| Worked sequences | ${sequences.length} |
| Focus areas with a ready plan / examples only / empty | ${count("Ready plan")} / ${count("Examples only")} / ${count("Start from 5E (empty)")} of ${coverage.length} |
| Game lessons at /play/ (published / draft or in review) | ${gamePublished.length} / ${game.lessons.length - gamePublished.length} |
| **Next action-plan item number** | **${nextItem}** |

## Published guides

Bump versions from these, never set a literal: patch for corrections, minor for added content,
no bump for a cross-reference (nesting) line only.

| Guide | id | Scale | Version | Last reviewed | Phases | Examples | Worked sequences |
|---|---|---|---|---|---|---|---|
${published.map((g) => `| ${g.name} | \`${g.id}\` | ${scale(g.reckoner.scale)} | ${g.version} | ${g.lastReviewed} | ${g.phases.length}${g.phaseGroups.length ? ` in ${g.phaseGroups.length} groups` : ""} | ${g.phases.reduce((n, p) => n + p.examples.length, 0)} | ${g.workedSequences.map((s) => `\`${s.id}\``).join(", ") || "none"} |`).join("\n")}
${drafts.length ? `\n## Draft and in-review guides\n\n${drafts.map((g) => `- \`${g.id}\` ${g.name}, v${g.version}, ${g.status}`).join("\n")}\n` : ""}
## Game lessons

Lessons for the game at \`/play/\`, from \`content/game/\`. Only published lessons reach students; bump
versions the same way as guides.

| Lesson | id | Path | Order | Level | Version | Status | Last reviewed | Items |
|---|---|---|---|---|---|---|---|---|
${game.lessons.map((l) => `| ${l.title} | \`${l.id}\` | \`${l.path}\` | ${l.order} | ${l.level} | ${l.version} | ${l.status} | ${l.lastReviewed} | ${l.items.length} |`).join("\n")}

## Models without a guide

These appear in the reckoner from \`content/catalogue.json\`, marked "guide coming soon". Adding a guide for
one means adding the guide and removing its catalogue entry in the same commit.

| id | Model | Scale |
|---|---|---|
${catalogue.filter((m) => !guideIds.has(m.id)).map((m) => `| \`${m.id}\` | ${m.name} | ${scale(m.scale)} |`).join("\n")}

## Model registry

Every id in \`MODEL_REGISTRY\` (\`scripts/validate.ts\`) and where it currently lives. Guide ids must match these.

| id | Model | Lives in |
|---|---|---|
${registryRows.join("\n")}
${strays.length ? `\nCatalogue ids not in the registry: ${strays.map((s) => `\`${s}\``).join(", ")}\n` : ""}
## Focus-area coverage

What "Start with your unit" shows for each NSW Science 7–10 (2023) focus area.

| Stage | Focus area | Shows | Worked sequences | Examples |
|---|---|---|---|---|
${coverage.map((c) => `| ${c.st === "stage4" ? "Stage 4" : "Stage 5"} | ${c.fa} | ${c.result} | ${c.seqs.map((s) => `\`${s.guide}:${s.id}\``).join(", ") || "—"} | ${c.exs.length} |`).join("\n")}

## Phases with no examples

Authoring targets. A guide with phase groups needs a positive and a negative example once per group, not per phase.

${emptyPhases.length ? emptyPhases.map((p) => `- ${p}`).join("\n") : "None."}

## Nesting links to models without a guide

These show as "guide coming soon" links inside published guides.

${comingSoon.length ? comingSoon.map((c) => `- ${c}`).join("\n") : "None."}

## Scripts

Run from \`tools/reckoner\`: ${Object.keys(pkg.scripts).map((s: string) => `\`npm run ${s}\``).join(", ")}.
`;

if (check) {
  const current = existsSync(OUT) ? readFileSync(OUT, "utf8") : "";
  if (current !== md) {
    console.error("docs/reckoner-state.md is out of date. Run npm run status (or npm run publish:pages) and commit it.");
    process.exit(1);
  }
  console.log("docs/reckoner-state.md is up to date.");
} else {
  writeFileSync(OUT, md);
  console.log(`Wrote docs/reckoner-state.md: ${published.length} guides, ${examples.length} examples, next action-plan item ${nextItem}.`);
}
